export const QUESTIONS = [
  {
    id: 'cin_2001',
    type: 'numeric',
    question: "Quanti film ha diretto come regista Stanley Kubrick?",
    min: 0,
    max: 50,
    step: 1,
    unit: 'film',
    correctValue: 13,
    explaination: [
      "Kubrik ha lavorato in diversi film come regista, scenggiatore, produttore ed altri ruoli. Tuttavia i film che diretto sono 13:",
      "Paura e desiderio (1953)",
      "Il bacio dell'assassino (1955)",
      "Rapina a mano armata (1956)",
      "Orizzonti di gloria (1957)",
      "Spartacus (1960)",
      "Lolita (1962)",
      "Il dottor Stranamore (1964)",
      "2001: Odissea nello spazio (1968)",
      "Arancia meccanica (1971)",
      "Barry Lyndon (1975)",
      "Shining (1980)",
      "Full Metal Jacket (1987)",
      "Eyes Wide Shut (1999)",
    ],
  },
  {
    id: 'cin_2002',
    type: 'numeric',
    question: "Quante stagioni ha la serie tv 'Breaking Bad'",
    min: 1,
    max: 10,
    step: 1,
    unit: 'stagioni',
    correctValue: 5,
    explaination: [
      "La serie tv 'Breaking Bad' è composta da 5 stagioni uscite in Italia dal 2008 al 2013.",
    ],
  },
  {
    id: 'cin_2003',
    type: 'numeric',
    question: "Quanti hanno ha Scorza, la tartaruga di 'Alla ricerca di Nemo'?",
    min: 1,
    max: 200,
    step: 1,
    unit: 'anni',
    correctValue: 150,
    explaination: [
      "Scorza è una tartaruga marina di 150 anni. Le tartarughe marine possono arrivare a vivere fino a 200 anni.",
      "Nonostante l'età, Scorza si crede e si comporta ancora come un ragazzino",
      "Nel film accompagna Marlin sul suo guscio; durante il viaggio riesce a fargli capire che l'essere troppo apprensivi con i propri figli sia sbagliato"
    ],
  },
]